-- =============================================================================
--  One-file build
-- =============================================================================
--  Packs the whole configuration into a single Lua file, to use on a machine
--  where cloning the repository is not worth it:
--
--    nvim -l scripts/bundle.lua [output]      (from the repository root;
--                                              output defaults to pure.lua)
--    nvim -u pure.lua                         (use it, or copy it to
--                                              ~/.config/nvim/init.lua)
--
--  Every module under lua/ becomes a package.preload entry with its code
--  unchanged, and init.lua's loader (between its [bundle:loader] markers)
--  becomes a fixed list of those modules, in the same order. The files that
--  are not Lua modules (colors/, snippets/, docs/) are embedded and unpacked
--  into stdpath('cache')/pure-bundle on start, which goes on the runtimepath
--  and is announced as vim.g.pure_bundle_dir.
--
--  Portable mode (vim.g.pure_portable, on by default in the built file):
--  modules that download plugins (they call vim.pack.add: plugins/*, the
--  extra themes) are skipped, so nothing is downloaded. Set
--  vim.g.pure_portable = false before it runs to get everything.
--
--  Do not edit the built file: change the modules and build again.
-- =============================================================================

local out_path = arg[1] or 'pure.lua'

local function read(path)
  local f = assert(io.open(path, 'rb'))
  local data = f:read('*a')
  f:close()
  return data
end

--- `data` as a Lua long string whose brackets do not occur inside it.
local function longString(data)
  local level = 0
  while data:find(']' .. string.rep('=', level) .. ']', 1, true) do level = level + 1 end
  local eq = string.rep('=', level)
  -- A newline right after the opening bracket is dropped by Lua; add one so
  -- data starting with a newline keeps it.
  return '[' .. eq .. '[\n' .. data .. ']' .. eq .. ']'
end

local function git(args)
  local res = vim.system(vim.list_extend({ 'git' }, args), { text = true }):wait()
  return res.code == 0 and vim.trim(res.stdout) or '?'
end

-- Modules, in the order init.lua loads them (glob order of their paths).
local modules = {}
for _, path in ipairs(vim.fn.glob('lua/**/*.lua', true, true)) do
  path = vim.fs.normalize(path)
  local name = path:sub(#'lua/' + 1):gsub('%.lua$', ''):gsub('/', '.')
  local code = read(path)
  table.insert(modules, { name = name, path = path, code = code, downloads = code:find('vim.pack.add', 1, true) ~= nil })
end
assert(#modules > 0, 'run from the repository root')

-- Files that are not modules, unpacked at start.
local files = {}
for _, pattern in ipairs({ 'colors/*.lua', 'snippets/*', 'docs/*.md' }) do
  for _, path in ipairs(vim.fn.glob(pattern, true, true)) do
    table.insert(files, { path = vim.fs.normalize(path), data = read(path) })
  end
end

local init = read('init.lua')
local s = init:find('%-%- %[bundle:loader%]')
local _, e = init:find('%-%- %[/bundle:loader%][^\n]*\n')
assert(s and e, 'init.lua has no [bundle:loader] markers')

local out = {}
local function add(text) table.insert(out, text) end

add(([[
-- =============================================================================
--  pure-nvim, the whole configuration in one file
-- =============================================================================
--  GENERATED by scripts/bundle.lua from %s @ %s (%s). Do not edit: change
--  the repository and build again. Documentation: the docs/ pages, embedded
--  below and listed by <leader>fh.
--
--    nvim -u pure.lua              try it
--    ~/.config/nvim/init.lua       or install it as the config
--
--  Portable mode is on: plugins and extra themes are not downloaded. Put
--    vim.g.pure_portable = false
--  on the line below to install and load everything.
-- =============================================================================
if vim.g.pure_portable == nil then vim.g.pure_portable = true end
]]):format(git({ 'rev-parse', '--abbrev-ref', 'HEAD' }), git({ 'rev-parse', '--short', 'HEAD' }),
  os.date('%Y-%m-%d')))

-- Unpack the embedded files (only when they changed) and put them on the
-- runtimepath: :colorscheme needs colors/ there.
add('\n-- Embedded files: colors/, snippets/, docs/\ndo\n  local files = {\n')
for _, f in ipairs(files) do
  add(('    [%q] = %s,\n'):format(f.path, longString(f.data)))
end
add([[
  }
  local dir = vim.fs.normalize(vim.fn.stdpath('cache')) .. '/pure-bundle'
  for path, data in pairs(files) do
    local target = dir .. '/' .. path
    local f = io.open(target, 'rb')
    local old = f and f:read('*a')
    if f then f:close() end
    if old ~= data then
      vim.fn.mkdir(vim.fs.dirname(target), 'p')
      f = assert(io.open(target, 'wb'))
      f:write(data)
      f:close()
    end
  end
  vim.opt.runtimepath:prepend(dir)
  vim.g.pure_bundle_dir = dir
end
]])

add('\n-- Modules\n')
for _, m in ipairs(modules) do
  add(('\n-- %s\npackage.preload[%q] = function(...)\n%s\nend\n'):format(m.path, m.name, m.code))
end

add('\n-- init.lua\n')
add(init:sub(1, s - 1))
add('local failures = {}\nlocal modules = {\n')
for _, m in ipairs(modules) do
  add(('  { %q, %s },\n'):format(m.name, tostring(m.downloads)))
end
add([[
}
for _, m in ipairs(modules) do
  -- Portable: skip what would download plugins.
  if not (vim.g.pure_portable and m[2]) then
    local ok, err = pcall(require, m[1])
    if not ok then table.insert(failures, m[1] .. ': ' .. tostring(err)) end
  end
end
]])
add(init:sub(e + 1))

local text = table.concat(out)
-- Refuse to write something that does not even parse.
assert(loadstring(text, '=' .. out_path))
local f = assert(io.open(out_path, 'wb'))
f:write(text)
f:close()

local skipped = vim.tbl_map(function(m) return m.name end, vim.tbl_filter(function(m) return m.downloads end, modules))
print(('%s: %d modules, %d files, %d KB; skipped when portable: %s'):format(
  out_path, #modules, #files, math.floor(#text / 1024), table.concat(skipped, ', ')))
